Feat/scripts
JakJaj/Stronghold-Guardians pull request #1
Opened 2024-04-04 09:03 UTC by V3X3N

Dodałem pierwsze proste kody:
- Waypoints: odpowiada za sterowanie przeciwnikiem po mapie,
- Enemy: prosty ruch przeciwnika, wykorzystuje Waypoints do poruszania się trasą,
- WaveSpawner: spawnuje przeciwników w fali, są również ustawione indeksy i rozmiar każdej fali,
- Turret: Prosty skrypt wieżyczki, celowanie i obracanie się w kierunku najbliższego przeciwnika.

2024-04-04 11:07 UTC, JakJaj commented
Jeszcze nie oglądałem tego kodu więc nie zrobię review ale polecam robić bardziej konkretne nazwy branczow niż scripts bo potem może być problem. Nie żeby to miała być jakaś rozprawka ale tak coś bardziej unikalnego. Tak tylko sugeruje.

2024-04-04 14:21 UTC, Wojtazik1 commented
Wyglada GIT

2024-04-04 15:54 UTC, JakJaj requested changes
Reszta rzeczy które nie działają to chyba kwestia tego że tylko jest skrypt i nie robiłeś nic w samym unity ale tego się tylko domyślam. Bo na tym poradniku z tego co oglądałem niektóre rzeczy wyglądały inaczej ale może poszedłeś dalej niż mi się wydawało

2024-04-04 15:54 UTC, JakJaj commented on Assets/Scripts/Enemy.cs
> +        if (Vector3.Distance(transform.position, target.position) <= 0,4f)
Tak się nie zapisuje floatów. I przez to ten kod się nie skompiluje.

2024-04-05 08:29 UTC, V3X3N commented
poprawiłem chyba wszystko co trzeba, teraz tylko powinien krzyczeć, że nie ma Wave i GameManager, ale to są obiekty do stworzenia w samym Unity więc powinno działać jak wy to zrobicie.

2024-04-05 09:56 UTC, JakJaj approved these changes
Z samego kodu to wyglada ok, jesli mowisz ze ten kod ktorego nie ma jest do dopisania dopiero to mozna to zaakceptowac

2024-04-05 12:10 UTC, Wojtazik1 approved these changes
Skoro mówisz że czekasz na nas to niech tak będzie

2024-04-05 12:15 UTC, merged