Feat/gui
JakJaj/Stronghold-Guardians pull request #12
Opened 2024-05-20 23:36 UTC by V3X3N

Oto nadszedł moment, kiedy udało się ukończyć sklep.

Generalna rozpiska do raportu na potem:
* Dodano interaktywne UI z możliwością wyboru, jaki turret chcemy kupić,
* Dodano podświetlanie node'a na czerwono w przypadku, gdy nie mamy pieniędzy,
* Dodano ceny każdego turreta z możliwością modyfikacji z poziomu Unity,
* Dodano wyświetlany czas do następnej fali z dokładnością do dwóch miejsc po przecinku,
* Lekko polepszono ścieżkę, po której poruszają się UFO,
* Dodano kilka nowych fontów na potem,
* Jeśli komuś dalej nie podświetla składni czy nie daje snippetów, to dodane zostały pakiety w Unity.

2024-05-21 00:59 UTC, JakJaj commented
Nie wiem co ale coś się sypie. Po pullnięciu tego brancha robie status i git mówi że wszystko działa. 

Wchodzę w Unity i naglę usuwa się plik Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss.meta. Tak po prostu. 

Przez co nie da się nic włączyć. Robie git restore .  żeby ten plik wrócił i dupa jak wchodzę w unity to przestaje działać. 

Nie wiem co robi ten plik ale no nie chce przez to u mnie działać to całe ustrojstwo. 
Może nie mam jakiegoś package ale nie wydaje mi się żeby przez to miałyby mi znikać plik. 

Dopisz jakie dodałeś pakiety to zobaczymy czy jak je pobiorę to zacznie to ze mną współpracować.

https://github.com/JakJaj/Stronghold-Guardians/assets/134608247/a9fd96e2-0848-444f-9765-941e5a295a9d

2024-05-21 09:00 UTC, V3X3N commented
![Zrzut ekranu 2024-05-21 105620](https://github.com/JakJaj/Stronghold-Guardians/assets/32016446/df2ae269-224f-42d5-8085-3d6ab67456be)
![Zrzut ekranu 2024-05-21 105638](https://github.com/JakJaj/Stronghold-Guardians/assets/32016446/21b03391-07dc-4931-84b0-2a47d5fae60d)

Dodałem jedynie te dwa pakiety, nic więcej, wątpie by to o to chodziło

2024-05-21 13:08 UTC, JakJaj commented
Myślałem że to jakieś pakiety do UI bo jakby nie było jest to plik z UI Toolkit. Możesz poszukać czemu się tak dzieje bo inaczej nie da się sprawdzić jak to działa

2024-05-21 16:38 UTC, JakJaj commented
Ok, dla potomnych. 

Żeby naprawić to o czym mowa trzeba wejść w folder UI Toolkit/UnityThemes i tam  PPP > Create > UI Toolkit > Default Runtime Theme File i nazwać go tak samo jak ten plik który znika. Wtedy git pokaże że tego pliku nie usunięto tylko go zmodyfikowano. Wchodzimy jeszcze raz w unity żeby sprawdzić czy pliczek zostaje. Jeśli tak to robimy git restore na tym pliku i powinno wtedy działać.

2024-05-21 16:46 UTC, JakJaj commented
Jeśli chodzi o sam ten sklep to przychodzą mi następujące rzeczy do głowy:

- po kupieniu wieży dostajemy błąd: UnassignedReferenceException
![Zrzut ekranu 2024-05-21 o 18 39 17](https://github.com/JakJaj/Stronghold-Guardians/assets/134608247/f20b0201-43a9-41c8-af43-6f6db5f47898)
- obrazek z balistą jest zauważalnie większy od reszty więc zmniejszyłbym ją.
- dodałbym jakiś sposób zaznaczenia że aktualnie wybraliśmy konkretny rodzaj wieży bo bez tego nie wiadomo co wybraliśmy i czy wgl wybraliśmy.
- do tego zaznaczania dodałbym opcje odznaczania tzn. kiedy naciśnie się PPM to odznacza się wybrana wieża i klikanie LPM na mapie nic nie wstawia
- dodałbym jakiś oznaczenie do cen i zebranych surowców. Czy np mamy $100 albo 100€ albo 100PKT albo 100 Gold a może dodać ikonke jakiejś monety czy sztabek złota. Coś takiego

2024-05-21 16:56 UTC, JakJaj requested changes
Jeśli chodzi o sam ten sklep to przychodzą mi następujące rzeczy do głowy:

- po kupieniu wieży dostajemy błąd: UnassignedReferenceException
![Zrzut ekranu 2024-05-21 o 18 39 17](https://github.com/JakJaj/Stronghold-Guardians/assets/134608247/f20b0201-43a9-41c8-af43-6f6db5f47898)
- obrazek z balistą jest zauważalnie większy od reszty więc zmniejszyłbym ją.
- dodałbym jakiś sposób zaznaczenia że aktualnie wybraliśmy konkretny rodzaj wieży bo bez tego nie wiadomo co wybraliśmy i czy wgl wybraliśmy.
- do tego zaznaczania dodałbym opcje odznaczania tzn. kiedy naciśnie się PPM to odznacza się wybrana wieża i klikanie LPM na mapie nic nie wstawia
- dodałbym jakiś oznaczenie do cen i zebranych surowców. Czy np mamy $100 albo 100€ albo 100PKT albo 100 Gold a może dodać ikonke jakiejś monety czy sztabek złota. Coś takiego
- Obok labelu z aktualnie posiadanymi surowcami dodałbym jakąś formę zaznaczenia że to jest nasz aktualny stan konta surowców czy czegoś bo troche losowo wygląda ta liczba tak bez żadnej informacji.
- Ostatnia taka wizualna rzecz to podniósł bym kamerę startową nieco wyżej. Tak żeby sklep był startowo na wodzie ale żeby było bliżej lądu bo robi się startowo dużo pustego miejsca i takie to jakieś nie równe.
- Takie coś małego i mało priorytetowego. Fajnie by było gdyby ruszanie się kamerą miało jakieś ograniczenia. W sensie żeby na max scrollu nie dało się wyjść kamerą poza mapę.

Więc praktycznie wszystko to rzeczy stricte kosmetyczne oprócz tego ostatniego. Jeśli chodzi o samą logikę sklepu to wygląda na to że działa.

2024-05-22 14:53 UTC, JakJaj commented
**Jest konflikt!**

Jeśli @V3X3N podpiąłeś dźwięki / muzykę to zostają zmiany z Twojego brancha a usuwasz GUID które są zaznaczone jako te z maina. Jeśli nic z tym nie zrobiłeś to obojętnie które bo nic to nie zmienia. 

Ergo - najbezpieczniej jest wywalić rzeczy z main i zostawić z tego brancha żeby przeszły na main.

Nawet jeśli bardzo się posypię to łatwo to naprawić. Niemniej lepiej nie musieć naprawiać.

2024-05-22 14:57 UTC, V3X3N commented
Nic nie było podpinane z muzyki ani dźwięków.
Jedyne co to wziąłem te strzałę, mogłem wtedy coś nieumyślnie zamieszać.

2024-05-22 15:00 UTC, JakJaj commented
To jest dlatego bo jak wstawiałem dźwięki to nie wszedłem w unity żeby się te meta pliki zrobiły. A teraz jak dołączyliśmy branch od @Wojtazik1 to się one dodały a Ty miałeś ze swojego brancha. Bo te guid się generuję. Ale jeśli nie podpinałeś nic to jak będziesz to rozwiązywał to obojętnie które wybierzesz.

2024-05-23 08:17 UTC, V3X3N commented
Mały disclaimer na start. Nie zamykajcie mi brancha, bo chce jeszcze wrzucić na niego albo jakieś UI (Game Over / Menu Pauzy) czy ulepszenia turretow nim pójdę do roboty.

Stosując się do porad od @JakJaj usprawniłem projekt, dlatego przesyłam teraz by można było sprawdzić.
* Naprawiłem error związany z BuildEffect;
* Naprawiłem wygląd ikonki balisty;
* Zmodyfikowana kamera - dodano ograniczenia poruszania się na boki *(można zmodyfikować limity w samym Unity)*;
* Przypadkiem, ale myślę też może tak być, zrobiłem że wieżyczki budują się pojedyńczo, to jest trzeba za każdym razem wybierać wieżyczkę by ją zbudować *(zamiast zaznaczania i odznaczania)*;
* Usprawniony wygląd UI, dodatkowo rozszerzony o nowe ikonki;
* Dodatkowo oprócz poprawek, dodałem prostą ekonomię *(dostajemy pieniążki za zabicie wroga)* oraz system życia opponent'ów;
* Trochę poprawiłem balans turret'ow, ale to też zawsze można zmienić;

2024-05-23 12:24 UTC, JakJaj commented
Wygląda dobrze. 

Jeśli miałbym się do czegoś przyczepiać to jakaś forma zaznaczenia że aktualnie mamy zaznaczoną wieżyczkę jednak by się przydała. I nie wiem czy fajne jest to że jak najeżdża się na zegar i pieniążek to one też się tak podnoszą. 

Wydaje mi się że też że to automatyczne odklikiwanie po kupieniu jest irytującą mechaniką ale to też nie ma co się tym tak przejmować. 

Co do balansowania to tym się będziemy przejmowali jak będą życia przeciwników i się zrobi myk że (jeśli będzie się dało):

- cannon będzie tani ale będzie miał mid szybkostrzelność i mid dmg
- balista będzie strzelała szybciej i mid obrażenia
- katapulta będzie miała duże obrażenia i będzie miała mid szybkostrzelność

To taki przykład. Ale still jest to rzecz którą będzie się można przejmować na samym końcu.

Póki co trzeba dowieść rzeczy na jutro i zrobić raporty @BartoszDeszcz . Jak będziesz miał wszystko ready na tym branchu to daj znać to się to jeszcze raz sprawdzi i będziemy mergować.

REMINDER:
Jak będziecie robili etapy gry to kolejność jest taka: LATO -> JESIEN -> ZIMA -> WIOSNA. Ale to chyba będzie na ostatnie dwa tygodnie zabawa.

2024-05-31 09:49 UTC, V3X3N commented
Siema

Skończyłem UI, a przynajmniej tak mi się wydaje.
Jak sprawdzicie to, to można merge zrobić i @BartoszDeszcz może podpinać wszystko pod pozostałe mapy.

A więc co zrobiłem:
* Zmieniłem na czas testów ilość życia gracza i prędkość opponent'ów;
* Poprawki w UI sklepu *(tam nie działało odliczanie do fali, już działa);
* Stworzyłem całe GameOver, mamy tam możliwość powrotu do Menu i rozpoczęcia od nowa;
* Stworzyłem całe menu pauzy, mamy tam możliwość kontynuacji, od nowa lub menu główne *(Pauzę odpalamy i zamykamy ESC)*;
* Przy pauzie i GameOver, kamera się zatrzymuje;
* Główne Menu jest przystosowane do odpalania wszystkich 4 map;
* Dodałem **limit FPS** na 60, tak by na pewno każdemu chodziło;
* Dodatkowo poprawki błędów i improvements do obecnego już kodu;

2024-05-31 12:37 UTC, JakJaj approved these changes
Jak sprawdzam to wydaje sie to działać tak jak powinno. Coraz bliżej finish.

2024-05-31 13:36 UTC, Wojtazik1 approved these changes
Wszystko fajnie dziala

2024-05-31 13:46 UTC, merged