add two types of bullets
JakJaj/Stronghold-Guardians pull request #6
Opened 2024-04-25 22:48 UTC by Wojtazik1

Dodalem kamien i kule armatnia, na strzale przyjdzie pozniej pora

2024-04-26 07:55 UTC, JakJaj requested changes
Jest mały zonk bo z tych assetów nie usunąłeś źródła światła i kamery. 

Wiec przy każdym strzale mapa będzie się robiłą biała. 

Po prostu musisz w blenderze usuną te elementy bo inaczej będzie problem.

2024-04-26 20:40 UTC, Wojtazik1 commented
Naprawilem to swiatlo hula wszystko

2024-04-26 22:26 UTC, JakJaj approved these changes
Teraz wszystko pięknie działa.

2024-04-27 06:32 UTC, V3X3N approved these changes
elegancko

2024-04-27 06:32 UTC, merged