scripts for cannons
JakJaj/Stronghold-Guardians pull request #7
Opened 2024-04-26 11:31 UTC by BartoszDeszcz

- Skrypt strzelania wierzyczek,
- Skrypt pocisku
- Uderzanie pocisku w przeciwnika

2024-04-26 11:33 UTC, V3X3N approved these changes
Zaufam

2024-04-26 11:38 UTC, V3X3N requested changes
Plik Tuttet sypie errorami, więc sprawdź jeszcze raz

2024-04-26 12:17 UTC, JakJaj requested changes
Poprawiłem ten kod, podłącz go tego unity i sprawdz czy w momencie w którym idzie przeciwnik to czy wycelowuje w przeciwnika przynajmniej. 

Jak wojtek poprawi pociski to zrób żeby strzelał w przeciwnika.

2024-04-26 15:26 UTC, V3X3N commented
* Poprawiłem kod Turret
* Poprawiłem kod Bullet
* Zrobiłem prefaby z wierzyczek
* Ustawiłem je na mapie

2024-04-26 15:31 UTC, V3X3N commented
* Poprawiłem kod Turret
* Poprawiłem kod Bullet
* Zrobiłem prefaby z turretow
* Ustawiłem je na mapie

2024-04-26 15:32 UTC, V3X3N approved these changes

2024-04-26 22:28 UTC, JakJaj commented
![Zrzut ekranu 2024-04-27 o 00 27 43](https://github.com/JakJaj/Stronghold-Guardians/assets/134608247/523dca4f-09b1-4ccb-b45b-0a8ac148e7c2)
Nie wiem co to jest ale cały jak klikasz run to sypię takimi błędami.

2024-04-27 07:32 UTC, V3X3N commented
* Dodałem pocisk osobny do cannona i osobny do catapult
* Usunąłem z mapy ballista ponieważ nie ma jeszcze gotowego pocisku
* Dodałem efekt zniszczenia przeciwnika
* Przeciwnicy są obecnie na tzw. one-hit'a
* Zmieniłem kod do spawnowania fal - teraz respi na sztywno fale co 5 sekund _(Można zmienić w Unity sobie czas)_
* Utworzyłem prefaby z efektu i pocisków
* Uzupełniłem skrypty, drobne poprawki

2024-04-27 18:06 UTC, JakJaj approved these changes
Wszystko się zgadza. Jedyne nad czym się zastanawiam to czy nie byłoby warto zwiększyć nieco te wieżyczki. Bo mam wrażenie że są troche za małe. Ale to można jeszcze przegadać bo nie jest to nic najważniejszego na teraz. Oby do przodu.

2024-04-28 15:06 UTC, merged